### ISSUE TITLE
Minimize keepass window after QuckUnlock

### ISSUE THREAD

**Issue by popovn** [Rookiestyle/LockAssist#5]
Please add Global hot key for quick unlock only.
  without popup keepass window 

That will very helpful with browser addons which can connect to keepass  after unlock 
(kee for example)

**Comment by Rookiestyle** [comment]
I have difficulties linking this issue's subject to its description.

Based on the subject *Minimize keepass window after QuckUnlock* I understand you want KeePass to minimize right after you unlock a databasee as you use a browser integration plugin.
This can already be achieved by ticking checkbox *Minimize main window after opening a database*
<img src="https://user-images.githubusercontent.com/36454520/147360314-bfa4352a-d23a-4acd-a7ee-220be62e1c52.png" width="50%"></img>




Based on your description you're not asking for minimizing KeePass but for a global hotkey for quick unlock
Quick Unlock does not replace the standard way of KeePass unlocking a database.
Instead, it integrates into the standard unlock form and due to that it's not possible to have a hotkey for doing *only* quick unlock without reimplementing everything that KeePass does before and after unlocking a database.

Instead of another global hotkey I propose to create a feature request for your browser integration plugin (e. g.) and ask for a feature within it to trigger database unlocking.
I personally use KeePassNatMsg in combination with https://github.com/keepassxreboot/keepassxc-browser - KeePassXC browser supports locking/unlocking your database from within your browser

**Comment by Rookiestyle** [comment]
If you're request is about none of the two topics above but about something different, please add a comment with more details and I might reopen this issue

**Comment by popovn** [comment]
Sorry for my bad english.

I understand what hotkey for start unlock process  is hard to implement ((

Now i use ctl-alt-k for two situations:
- if i wanna save password from browser to base: after i quickunlock base - keepass window does not shown at screen but it "in focus" (worked ctrl-L shortcut for lock for example) - keepass does not give back focus to browser window - i must use mouse click or alt-tab twice to use keyboard on it.
- if i wanna see mine window of keepass - i use ctrl-alt-k to quikunlock and use ctrl-alt-k another time to show window 

For me ideal unlock is push ctrl-alt-l and without any dialog press 3 buttons (may be without "enter" as you know count of buttons from preferences )
Base will unlocked, any window doesnt shown

I will have a choice of three variants
- ctrl-alt-l  for unlock and use same integrations to keepass (as browser extention)
- ctrl-alt-k for open keepass window for work with base
- ctrl-alt-a for autotype (after quickunlock)

PS: autotype now after quickunlock doestn show any keepass windows and give back focus for window from which was launched

PPS: Sorry for you time - i understand what problem with focus - its problem of keepass hotkey system (if i unlock from browser extention by mouse click on icon -  focus is reverse back to browser after unlock)
